wultra/powerauth-tests

powerauth-backend-tests/src/main/java/com/wultra/security/powerauth/configuration/PowerAuthTestConfiguration.java
powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v3/PowerAuthActivationTest.java
powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v31/PowerAuthActivationTest.java

This change fixes collision between recovery and activation tests. I'm not 100% sure that I understand the purpose of `lookupActivationsInvalidStatusTest()`. In this fix, I expect that we're looking for activations at the particular state, but there's no such one.

Fix #12: Test for Lookup for activations

---

powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v31/PowerAuthApiTest.java

Two tests were failing because time was not synchronized exactly and there was a second or so difference between Prague and Azure server location. Increasing the time window to +-10 seconds for the history query fixes the issue.

Increase time synchronization window between server and client to 20 seconds

---

powerauth-test-server/README.md
powerauth-test-server/docs/sql/postgresql/create-schema.sql
powerauth-test-server/pom.xml
powerauth-test-server/src/main/java/com/wultra/security/powerauth/app/testserver/ServletInitializer.java
powerauth-test-server/src/main/java/com/wultra/security/powerauth/app/testserver/TestServerApplication.java
powerauth-test-server/src/main/java/com/wultra/security/powerauth/app/testserver/config/TestServerConfiguration.java
powerauth-test-server/src/main/java/com/wultra/security/powerauth/app/testserver/controller/ActivationController.java
powerauth-test-server/src/main/java/com/wultra/security/powerauth/app/testserver/controller/HomeController.java
powerauth-test-server/src/main/java/com/wultra/security/powerauth/app/testserver/database/TestConfigRepository.java
powerauth-test-server/src/main/java/com/wultra/security/powerauth/app/testserver/database/TestStatusRepository.java
powerauth-test-server/src/main/java/com/wultra/security/powerauth/app/testserver/database/entity/TestConfigEntity.java
powerauth-test-server/src/main/java/com/wultra/security/powerauth/app/testserver/database/entity/TestStatusEntity.java
powerauth-test-server/src/main/java/com/wultra/security/powerauth/app/testserver/errorhandling/ActivationFailedException.java
powerauth-test-server/src/main/java/com/wultra/security/powerauth/app/testserver/errorhandling/AppConfigNotFoundException.java
powerauth-test-server/src/main/java/com/wultra/security/powerauth/app/testserver/errorhandling/DefaultExceptionHandler.java
powerauth-test-server/src/main/java/com/wultra/security/powerauth/app/testserver/errorhandling/GenericCryptographyException.java
powerauth-test-server/src/main/java/com/wultra/security/powerauth/app/testserver/errorhandling/RemoteExecutionException.java
powerauth-test-server/src/main/java/com/wultra/security/powerauth/app/testserver/model/request/CreateActivationRequest.java
powerauth-test-server/src/main/java/com/wultra/security/powerauth/app/testserver/model/response/CreateActivationResponse.java
powerauth-test-server/src/main/java/com/wultra/security/powerauth/app/testserver/service/ActivationService.java
powerauth-test-server/src/main/java/com/wultra/security/powerauth/app/testserver/service/ResultStatusService.java
powerauth-test-server/src/main/java/com/wultra/security/powerauth/app/testserver/util/ResultStatusUtil.java
powerauth-test-server/src/main/resources/application.properties
powerauth-test-server/src/main/resources/templates/index.html

The pull request contains first version of the test server which can be used for testing of creating activations. Other features will be added later.

First version of test server with implementation of code-based activation

---

powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v31/PowerAuthOnboardingTest.java

Depends on https://github.com/wultra/enrollment-server/pull/323

Fix #94: Add test case to remove activation during cleanup

---

powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v31/PowerAuthIdentityVerificationTest.java

The changes are related to https://github.com/wultra/enrollment-server/pull/332.

Fix #96: Test for maximum attempts for OTP verification during SCA step

---

powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v31/PowerAuthIdentityVerificationTest.java
powerauth-backend-tests/src/test/resources/application.properties

I am done with parameter `documentVerificationOnSubmitEnabled`, this is causing neverending confusion and invalid configuration issues.
The document state does not currently reflect exactly what happened on server (document is already uploaded during synchronous processing, `UPLOAD_IN_PROGRESS` is the correct state only for async). I added similar TODO into backend code.

Remove obsolete parameter verifyOnSubmit

---

powerauth-test-server/src/main/java/com/wultra/security/powerauth/app/testserver/model/request/CreateTokenRequest.java
powerauth-test-server/src/main/java/com/wultra/security/powerauth/app/testserver/service/TokenService.java

This PR adds ability to create token with other than POSSESSION_KNOWLEDGE factors to Test Server.
There's new optional param `signatureType` and if it's omitted, then `POSSESSION_KNOWLEDGE` is used. This achieves a backward compatibility with previous tests.

Fix #147: Create token with other factors than possession+knowledge

---

powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v31/PowerAuthApiTest.java

This pull request introduces updated ECIES implementation for crypto 3.2.
The actual tests for crypto 3.2 will be implemented in a separate pull request, these changes only migrate tests to new ECIES interfaces and verify that no regressions were introduced.

Update ECIES implementation for crypto 3.2

---

powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v31/PowerAuthApiTest.java

This PR replaces usage of low level ECIES encryptor with new ClientEncryptor and ServerEncryptor interfaces.

Fix #226: Use general encryptor

---

pom.xml
powerauth-test-server/pom.xml

Fix #260
- dependencyManagement was edited in parent pom.xml to include tomcat transitive dependencies as provided
- Exclusions from the server's pom.xml dependencies was removed
- removed standalone profile from the server's pom
Using the new configuration, the test-server is executable using `java -jar` and tomcat dependencies are only in the `lib-provided` directory

Fix #260: Executable war

---

pom.xml
powerauth-fido2-tests/pom.xml
powerauth-fido2-tests/src/main/java/com/wultra/security/powerauth/fido2/controller/AssertionController.java
powerauth-fido2-tests/src/main/java/com/wultra/security/powerauth/fido2/controller/DefaultExceptionHandler.java
powerauth-fido2-tests/src/main/java/com/wultra/security/powerauth/fido2/controller/RegistrationController.java
powerauth-fido2-tests/src/main/java/com/wultra/security/powerauth/fido2/controller/request/AssertionOptionsRequest.java
powerauth-fido2-tests/src/main/java/com/wultra/security/powerauth/fido2/controller/request/RegisterCredentialRequest.java
powerauth-fido2-tests/src/main/java/com/wultra/security/powerauth/fido2/controller/request/RegistrationOptionsRequest.java
powerauth-fido2-tests/src/main/java/com/wultra/security/powerauth/fido2/controller/request/VerifyAssertionRequest.java
powerauth-fido2-tests/src/main/java/com/wultra/security/powerauth/fido2/controller/response/AssertionOptionsResponse.java
powerauth-fido2-tests/src/main/java/com/wultra/security/powerauth/fido2/controller/response/CredentialDescriptor.java
powerauth-fido2-tests/src/main/java/com/wultra/security/powerauth/fido2/controller/response/RegistrationOptionsResponse.java
powerauth-fido2-tests/src/main/java/com/wultra/security/powerauth/fido2/service/AssertionService.java
powerauth-fido2-tests/src/main/java/com/wultra/security/powerauth/fido2/service/Fido2SharedService.java
powerauth-fido2-tests/src/main/java/com/wultra/security/powerauth/fido2/service/RegistrationService.java
powerauth-fido2-tests/src/main/java/com/wultra/security/powerauth/fido2/service/SharedService.java

Backend part of the FIDO test app. The endpoints are called from javascript to build webauthn ceremony options or to make assertion / registration at the server.  
The shared service contains methods to list templates or applications name, which are further used in the UI.
Frontend part will be added in the next issue.

Fix #379: FIDO2 Test application: Backend

---

powerauth-fido2-tests/pom.xml
powerauth-fido2-tests/src/main/java/com/wultra/security/powerauth/fido2/service/AssertionService.java
powerauth-fido2-tests/src/main/webapp/resources/js/webauthn.js
powerauth-fido2-tests/src/test/java/com/wultra/security/powerauth/fido2/service/AssertionServiceTest.java

Fix #388 
The operation data are split into two 32B arrays padded with `*`. The algorithm is:
```
Input: operationData (e.g.: A1*A21CZK*ICZ5508000000001234567899)
If |operationData| <= 64B, add padding to fill 64B array and split into two 32B arrays.
Else:
1. Parse operation data fields
2. Create croppedOperationData, initiate it with header (e.g. croppedOperationData := "A1")
3. While |croppedOperationData| <= 64B, try to append operation data field ordered by priority ("I", "Q", "A", "R", "D", "N")
4. To croppedOperationData add padding to fill 64B array and split into two 32B arrays.
```

Fix #388: FIDO2 Test application: Sharing operation data

---

powerauth-fido2-tests/src/main/java/com/wultra/security/powerauth/fido2/service/AssertionService.java
powerauth-fido2-tests/src/main/java/com/wultra/security/powerauth/fido2/service/Fido2SharedService.java
powerauth-fido2-tests/src/main/java/com/wultra/security/powerauth/fido2/service/RegistrationService.java

Reflect changes introduced in https://github.com/wultra/powerauth-server/issues/1374 and https://github.com/wultra/powerauth-server/issues/1391
On top of that the credential ID is not transported to the remote server in base64

Fix #391: FIDO2 Test application: Names refactoring

---

powerauth-fido2-tests/src/main/java/com/wultra/security/powerauth/fido2/service/AssertionService.java
powerauth-fido2-tests/src/main/webapp/resources/js/webauthn.js
powerauth-fido2-tests/src/test/java/com/wultra/security/powerauth/fido2/service/AssertionServiceTest.java

Remove `hmacGetSecret` extension and its relevant code. Keep the `txAuthSimple` for visual inspection of operation data in browser console. Append credential holding operation data if there is usb transport in allow credentials.

Fix #394: FIDO2 Test Application: Adopt new approach of sharing operation data

---

powerauth-fido2-tests/src/main/java/com/wultra/security/powerauth/fido2/controller/request/RegisterCredentialRequest.java
powerauth-fido2-tests/src/main/java/com/wultra/security/powerauth/fido2/controller/request/VerifyAssertionRequest.java
powerauth-fido2-tests/src/main/java/com/wultra/security/powerauth/fido2/service/AssertionService.java
powerauth-fido2-tests/src/main/java/com/wultra/security/powerauth/fido2/service/RegistrationService.java
powerauth-fido2-tests/src/main/webapp/resources/js/webauthn.js

- `userHandle` in attestation [can be null](https://w3c.github.io/webauthn/#iface-authenticatorassertionresponse).
- `authenticatorAttachement` in both ceremonies [can be null](https://w3c.github.io/webauthn/#iface-pkcredential).

Fix #401: FIDO2 Test Application: nullable parameters

---

pom.xml
powerauth-backend-tests/pom.xml
powerauth-load-tests/pom.xml
powerauth-test-server/pom.xml
powerauth-webflow-tests/pom.xml

Use transient dependency from `powerauth-crypto`.

Fix #418: Refactor BouncyCastle dependency

---

powerauth-fido2-tests/src/main/java/com/wultra/security/powerauth/fido2/controller/AssertionController.java
powerauth-fido2-tests/src/main/java/com/wultra/security/powerauth/fido2/controller/HomeController.java
powerauth-fido2-tests/src/main/java/com/wultra/security/powerauth/fido2/controller/request/AssertionOptionsRequest.java
powerauth-fido2-tests/src/main/java/com/wultra/security/powerauth/fido2/controller/request/RegisterCredentialRequest.java
powerauth-fido2-tests/src/main/java/com/wultra/security/powerauth/fido2/controller/request/RegistrationOptionsRequest.java
powerauth-fido2-tests/src/main/java/com/wultra/security/powerauth/fido2/service/AssertionService.java
powerauth-fido2-tests/src/main/java/com/wultra/security/powerauth/fido2/service/RegistrationService.java
powerauth-fido2-tests/src/main/resources/templates/login.html
powerauth-fido2-tests/src/main/resources/templates/payment.html
powerauth-fido2-tests/src/main/webapp/resources/js/login.js
powerauth-fido2-tests/src/main/webapp/resources/js/payment.js
powerauth-fido2-tests/src/main/webapp/resources/js/webauthn.js

In previous version username was the primary identificator of a user. A user could include username only, which was then in registration process used as user.id, user.name and user.displayName in registration ceremony.    
Now the role of primary identificator is User ID, but user is able to change their username or display name for the registration process.  
If only user ID is set, username and display name is set to user ID.

Fix #430: FIDO2 Test: User details input options

---

powerauth-fido2-tests/src/main/resources/templates/login.html

Change WebAuthN default options to fit wultra authenticator

Fix #435: FIDO2 Test App: Change default webauthn options

---

pom.xml
powerauth-fido2-tests/src/main/java/com/wultra/security/powerauth/fido2/service/AssertionService.java
powerauth-fido2-tests/src/main/java/com/wultra/security/powerauth/fido2/service/Fido2SharedService.java
powerauth-fido2-tests/src/main/java/com/wultra/security/powerauth/fido2/service/RegistrationService.java

to have working fido testing app on 1.7.x
(cherry picked from commit df8e9384f13539e3e7ba0c34f3525f684e4e0401)

Fix #428: FIDO2 Test: Pass excludeCredentials list from challenge response (backport) (#429)

---

powerauth-fido2-tests/src/main/java/com/wultra/security/powerauth/fido2/controller/HomeController.java
powerauth-fido2-tests/src/main/resources/application.properties
powerauth-fido2-tests/src/main/resources/templates/embeddedLogin.html
powerauth-fido2-tests/src/main/resources/templates/embeddedPayment.html
powerauth-fido2-tests/src/main/resources/templates/forms/loginForm.html
powerauth-fido2-tests/src/main/resources/templates/forms/paymentForm.html
powerauth-fido2-tests/src/main/resources/templates/login.html
powerauth-fido2-tests/src/main/resources/templates/payment.html
powerauth-fido2-tests/src/main/webapp/resources/js/login.js
powerauth-fido2-tests/src/main/webapp/resources/js/payment.js

When a page is loaded with `?embedded=true` query parameter, only the form with transparent background is shown for convenient iframe embedding. 
Added setting `SameSite=None` for cookies, otherwise the interactive login in embedded frame would not work properly because of 3rd party cookie blocking.

Fix #508: FIDO2 Test application: Embeddable form

---

.github/workflows/develop_pa-test-internal-testserver-app.yml

(cherry picked from commit 8cb6d577a1f0e7c0159db4edbda4c7d5e8cc357e)

Fix #565 Standardize pipeline for deployment of test-server and add option to deploy to dockerhub
