powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v3/PowerAuthMigrationTest.java

Fix #3: Implement tests for migration

---

LICENSE
README.md
powerauth-backend-tests/pom.xml
powerauth-backend-tests/src/main/java/com/wultra/security/powerauth/PowerAuthTestApplication.java
powerauth-backend-tests/src/main/java/com/wultra/security/powerauth/configuration/PowerAuthTestConfiguration.java
powerauth-backend-tests/src/main/java/com/wultra/security/powerauth/configuration/SecurityConfiguration.java
powerauth-backend-tests/src/main/java/com/wultra/security/powerauth/configuration/WebApplicationConfiguration.java
powerauth-backend-tests/src/main/java/com/wultra/security/powerauth/provider/CustomActivationProvider.java
powerauth-backend-tests/src/main/java/com/wultra/security/powerauth/provider/CustomActivationProviderForTests.java
powerauth-backend-tests/src/main/java/com/wultra/security/powerauth/test/PowerAuthTestSetUp.java
powerauth-backend-tests/src/main/java/com/wultra/security/powerauth/test/PowerAuthTestTearDown.java
powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/PowerAuthConfigurationTest.java
powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/PowerAuthHttpTest.java
powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v2/PowerAuthActivationTest.java
powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v2/PowerAuthSignatureTest.java
powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v2/PowerAuthTokenTest.java
powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v2/PowerAuthVaultUnlockTest.java
powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v3/PowerAuthActivationTest.java
powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v3/PowerAuthCustomActivationTest.java
powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v3/PowerAuthEncryptionTest.java
powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v3/PowerAuthSignatureTest.java
powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v3/PowerAuthTokenTest.java
powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v3/PowerAuthUpgradeTest.java
powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v3/PowerAuthVaultUnlockTest.java
powerauth-backend-tests/src/test/resources/application.properties

Merge stable tests into master.

Merge stable tests for PowerAuth release 0.21.0

---

powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v3/PowerAuthRecoveryTest.java
powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v31/PowerAuthRecoveryTest.java

This change adds a test for invalid recovery PUK. The branch is also called as "releases/0.23.x", because we forgot tag the release. We should not remove the branch after the merge.

Added test for invalid recovery PUK

---

powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v2/PowerAuthActivationTest.java
powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v3/PowerAuthActivationTest.java
powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v31/PowerAuthActivationFlagsTest.java
powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v31/PowerAuthActivationTest.java
powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v31/PowerAuthApiTest.java

Improve resilience against time desynchronization between client and server, use server time when possible.

Improve resilience against time desynchronization 

---

powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/PowerAuthHttpTest.java
powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v2/PowerAuthActivationTest.java
powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v2/PowerAuthSignatureTest.java
powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v2/PowerAuthTokenTest.java
powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v2/PowerAuthVaultUnlockTest.java
powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v3/PowerAuthActivationTest.java
powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v3/PowerAuthCustomActivationTest.java
powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v3/PowerAuthEncryptionTest.java
powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v3/PowerAuthRecoveryTest.java
powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v3/PowerAuthSignatureTest.java
powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v3/PowerAuthTokenTest.java
powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v3/PowerAuthUpgradeTest.java
powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v3/PowerAuthVaultUnlockTest.java
powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v31/PowerAuthActivationCodeTest.java
powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v31/PowerAuthActivationFlagsTest.java
powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v31/PowerAuthActivationOtpTest.java
powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v31/PowerAuthActivationTest.java
powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v31/PowerAuthApiTest.java
powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v31/PowerAuthApplicationRolesTest.java
powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v31/PowerAuthCallbackTest.java
powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v31/PowerAuthCustomActivationOtpTest.java
powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v31/PowerAuthCustomActivationTest.java
powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v31/PowerAuthEncryptionTest.java
powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v31/PowerAuthRecoveryTest.java
powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v31/PowerAuthSignatureTest.java
powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v31/PowerAuthTokenTest.java
powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v31/PowerAuthUpgradeTest.java
powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v31/PowerAuthVaultUnlockTest.java

Change visibility of test classes and methods to package private.
https://junit.org/junit5/docs/current/user-guide/#writing-tests-classes-and-methods

Change visibility of test classes and methods to package private

---

powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v31/PowerAuthIdentityVerificationTest.java

Depends on https://github.com/wultra/enrollment-server-wultra/pull/33

Fix #81: Change assert of consent

---

powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v31/PowerAuthIdentityVerificationTest.java

Depends on https://github.com/wultra/enrollment-server/pull/303 and https://github.com/wultra/enrollment-server-wultra/pull/37

Fix #88: Add tests for SCA

---

powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v31/PowerAuthOnboardingTest.java

Depends on https://github.com/wultra/enrollment-server/pull/300

Fix #85: Add a test for the onboarding process resume

---

powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v31/PowerAuthOnboardingTest.java

Depends on
- https://github.com/wultra/enrollment-server/pull/321
- https://github.com/wultra/enrollment-server-wultra/pull/42

Fix #92: Add test case to send OTP for non-existing user

---

powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v31/PowerAuthIdentityVerificationTest.java

Depends on https://github.com/wultra/enrollment-server/pull/331

Fix #98: Update test asserts because status endpoint changes

---

powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v31/PowerAuthIdentityVerificationTest.java

Depends on https://github.com/wultra/enrollment-server/pull/364

Fix #101: Submit two document types

---

powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v31/PowerAuthIdentityVerificationTest.java

Depends on https://github.com/wultra/enrollment-server/issues/397

Fix #107: Replace status OTP_VERIFICATION_PENDING by VERIFICATION_PENDING

---

powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v31/PowerAuthIdentityVerificationTest.java

Depends on https://github.com/wultra/enrollment-server/pull/390

Fix #105: Add PRESENCE_CHECK/VERIFICATION_PENDING

---

powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v31/PowerAuthEnrollmentConfigurationTest.java

Depends on https://github.com/wultra/enrollment-server/pull/409

Fix #111: Add test for mobile app version endpoint

---

powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v31/PowerAuthOnboardingTest.java

Test for remaining attempts during activation using OTP code verification.

Fix #100: Test for maximum failed OTP verification attempts

---

powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v31/PowerAuthIdentityVerificationTest.java

Depends on https://github.com/wultra/enrollment-server/pull/438

Fix #116: Change path to document/init-sdk

---

powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v31/PowerAuthIdentityVerificationTest.java
powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v31/PowerAuthOnboardingTest.java

Depends on https://github.com/wultra/enrollment-server/pull/482

Fix #80: Implement tests for onboarding process limits

---

powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v31/PowerAuthIdentityVerificationTest.java
powerauth-backend-tests/src/test/resources/application.properties

Depends on https://github.com/wultra/enrollment-server/pull/515

Fix #136: Update tests to adapt changes in document upload

---

powerauth-test-server/Dockerfile
powerauth-test-server/docker/powerauth-test-server.xml

* add health check valve
* limit DB pool size and age

add tomcat properties

---

powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v31/PowerAuthIdentityVerificationTest.java

Depends on https://github.com/wultra/enrollment-server/pull/535

Fix #142: Remove document status from submit tests

---

powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v31/PowerAuthEnrollmentConfigurationTest.java
powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v31/PowerAuthIdentityVerificationTest.java

Depends on https://github.com/wultra/enrollment-server/pull/531

Fix #140: Change test after revision of encryption

---

powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v31/PowerAuthIdentityVerificationTest.java

Depends on https://github.com/wultra/enrollment-server/pull/538

Fix #144: Update test for sync document submit

---

.github/workflows/maven-test-compile.yml
pom.xml
powerauth-backend-tests/pom.xml
powerauth-load-tests/pom.xml
powerauth-test-server/pom.xml
powerauth-webflow-tests/pom.xml
powerauth-webflow-tests/src/main/java/com/wultra/security/powerauth/webflow/test/PowerAuthTestSetUp.java

- Add parent pom
- Add GitHub action for test-compile
- Update Spring Boot to 2.7.8

Fix #157: Add a check for pull-requests

---

.github/workflows/maven-test-compile.yml

Add workflow_dispatch to maven-test-compile.yml

---

.github/workflows/maven-test-compile.yml

Fix maven-test-compile.yml

---

powerauth-backend-tests/src/main/java/com/wultra/security/powerauth/configuration/PowerAuthTestConfiguration.java
powerauth-backend-tests/src/main/java/com/wultra/security/powerauth/controller/CallbackTestController.java
powerauth-backend-tests/src/main/java/com/wultra/security/powerauth/provider/CustomActivationProviderForTests.java
powerauth-backend-tests/src/main/java/com/wultra/security/powerauth/test/PowerAuthTestSetUp.java
powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/PowerAuthConfigurationTest.java
powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/PowerAuthHttpTest.java
powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v3/PowerAuthRecoveryTest.java
powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v3/PowerAuthSignatureTest.java
powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v3/PowerAuthVaultUnlockTest.java
powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v31/PowerAuthActivationCodeTest.java
powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v31/PowerAuthApiTest.java
powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v31/PowerAuthIdentityVerificationTest.java
powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v31/PowerAuthOnboardingTest.java
powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v31/PowerAuthRecoveryTest.java
powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v31/PowerAuthSignatureTest.java
powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v31/PowerAuthUserInfoTest.java
powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v31/PowerAuthVaultUnlockTest.java
powerauth-test-server/src/main/java/com/wultra/security/powerauth/app/testserver/database/entity/TestConfigEntity.java
powerauth-test-server/src/main/java/com/wultra/security/powerauth/app/testserver/database/entity/TestStatusEntity.java
powerauth-test-server/src/main/java/com/wultra/security/powerauth/app/testserver/errorhandling/ActivationFailedException.java
powerauth-test-server/src/main/java/com/wultra/security/powerauth/app/testserver/errorhandling/AppConfigNotFoundException.java
powerauth-test-server/src/main/java/com/wultra/security/powerauth/app/testserver/errorhandling/GenericCryptographyException.java
powerauth-test-server/src/main/java/com/wultra/security/powerauth/app/testserver/errorhandling/RemoteExecutionException.java
powerauth-test-server/src/main/java/com/wultra/security/powerauth/app/testserver/model/request/ConfigureApplicationRequest.java
powerauth-webflow-tests/src/main/java/com/wultra/security/powerauth/webflow/configuration/WebFlowTestConfiguration.java
powerauth-webflow-tests/src/main/java/com/wultra/security/powerauth/webflow/test/PowerAuthTestSetUp.java
powerauth-webflow-tests/src/test/java/com/wultra/security/powerauth/webflow/test/LoginTest.java
powerauth-webflow-tests/src/test/java/com/wultra/security/powerauth/webflow/test/WebFlowConfigurationTest.java

- Fix incompatible asserts
- Remove unnecessary toString
- Add final modifier
- Replace conditional break in the loop
- Remove redundant throws
- Add @Serial annotation
- Simplify optional call
- Replace explicit type by diamond operator <>
- Remove unnecessary boxing
- Enhance switch

Fix #202: Review Java warnings

---

powerauth-backend-tests/src/main/java/com/wultra/security/powerauth/test/PowerAuthTestSetUp.java
powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v3/PowerAuthActivationTest.java
powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v3/PowerAuthCustomActivationTest.java
powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v3/PowerAuthEncryptionTest.java
powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v3/PowerAuthRecoveryTest.java
powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v3/PowerAuthSignatureTest.java
powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v3/PowerAuthTokenTest.java
powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v3/PowerAuthVaultUnlockTest.java
powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v31/PowerAuthActivationCodeTest.java
powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v31/PowerAuthActivationFlagsTest.java
powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v31/PowerAuthActivationOtpTest.java
powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v31/PowerAuthActivationTest.java
powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v31/PowerAuthCustomActivationOtpTest.java
powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v31/PowerAuthCustomActivationTest.java
powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v31/PowerAuthEncryptionTest.java
powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v31/PowerAuthIdentityVerificationTest.java
powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v31/PowerAuthOnboardingTest.java
powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v31/PowerAuthRecoveryTest.java
powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v31/PowerAuthSignatureTest.java
powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v31/PowerAuthTokenTest.java
powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v31/PowerAuthUserInfoTest.java
powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v31/PowerAuthVaultUnlockTest.java
powerauth-test-server/src/main/java/com/wultra/security/powerauth/app/testserver/service/ActivationService.java
powerauth-test-server/src/main/java/com/wultra/security/powerauth/app/testserver/service/OperationsService.java
powerauth-test-server/src/main/java/com/wultra/security/powerauth/app/testserver/service/SignatureService.java
powerauth-test-server/src/main/java/com/wultra/security/powerauth/app/testserver/service/TokenService.java
powerauth-test-server/src/main/java/com/wultra/security/powerauth/app/testserver/util/StepItemLogger.java
powerauth-webflow-tests/src/main/java/com/wultra/security/powerauth/webflow/test/PowerAuthTestSetUp.java

Follow-up to https://github.com/wultra/powerauth-cmd-tool/pull/304

Fix #205: Adapt changes in Step records

---

powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v31/PowerAuthApiTest.java

- Add testGetActivationListForUserPagination to test pageable behavior

Fix #220: Add test for Pageable for activationList

---

powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v31/PowerAuthApiTest.java

This PR fixes `PowerAuthApiTest` broken after changes in ECIES encryption.

Fix API tests

---

powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v3/PowerAuthSignatureTest.java

Depends on https://github.com/wultra/powerauth-server/pull/939

Fix #218: Add test of proximity anti-fraud check at offline mode

---

powerauth-test-server/pom.xml
powerauth-test-server/src/main/resources/application-dev.properties

- Set liquibase deps only as optional with mvn profile

Fix #276: Startup error from Liquibase for Test Server

---

powerauth-test-server/src/main/java/com/wultra/security/powerauth/app/testserver/controller/OperationsController.java

Document Accept-Language header for /operations/pending endpoint

---

.github/workflows/maven-deploy.yml

(cherry picked from commit 03952ca31ad711f9b108ec50c2fb16490f246623)

Add GitHub Action config maven-deploy.yml (backport)

---

pom.xml

Cherry-picked 6be064cc021311dec24bd35d1d65f898f6f7eb51

Add distribution management configuration (backport)

---

.github/workflows/maven-deploy.yml

(cherry picked from commit e4ae6ba62baec2916208e0c05a960fa2b98e3a99)

Specify directory_path in maven-deploy.yml (forwardport)

---

.github/workflows/maven-deploy.yml
.github/workflows/maven-integration-test.yml
.github/workflows/maven-test-compile.yml
powerauth-load-tests/pom.xml

Fix #382: Build with JDK 21 Fails

---

powerauth-fido2-tests/src/main/java/com/wultra/security/powerauth/fido2/configuration/PowerAuthWebServiceConfiguration.java
powerauth-fido2-tests/src/main/java/com/wultra/security/powerauth/fido2/controller/AssertionController.java
powerauth-fido2-tests/src/main/java/com/wultra/security/powerauth/fido2/controller/RegistrationController.java
powerauth-fido2-tests/src/main/java/com/wultra/security/powerauth/fido2/controller/request/RegisterCredentialRequest.java
powerauth-fido2-tests/src/main/java/com/wultra/security/powerauth/fido2/controller/request/VerifyAssertionRequest.java
powerauth-fido2-tests/src/main/java/com/wultra/security/powerauth/fido2/service/AssertionService.java
powerauth-fido2-tests/src/main/java/com/wultra/security/powerauth/fido2/service/Fido2SharedService.java
powerauth-fido2-tests/src/main/java/com/wultra/security/powerauth/fido2/service/RegistrationService.java

Depends on https://github.com/wultra/powerauth-server/pull/1444

Fix #404: Refactor to use module fido2-model

---

powerauth-fido2-tests/src/main/java/com/wultra/security/powerauth/fido2/service/AssertionService.java
powerauth-fido2-tests/src/main/java/com/wultra/security/powerauth/fido2/service/Fido2SharedService.java
powerauth-fido2-tests/src/main/java/com/wultra/security/powerauth/fido2/service/RegistrationService.java

Depends on:
- https://github.com/wultra/powerauth-server/issues/1502

Fix #428: FIDO2 Test: Pass excludeCredentials list from challenge response

---

docs-private/Performance-Testing-Guide.md
powerauth-load-tests/pom.xml
powerauth-load-tests/src/test/java/com/wultra/security/powerauth/test/config/PowerAuthLoadTestCommon.java
powerauth-load-tests/src/test/java/com/wultra/security/powerauth/test/model/UserRegistrationInfo.java
powerauth-load-tests/src/test/java/com/wultra/security/powerauth/test/scenario/CreateApproveOperationScenario.java
powerauth-load-tests/src/test/java/com/wultra/security/powerauth/test/scenario/CreateOperationScenario.java
powerauth-load-tests/src/test/java/com/wultra/security/powerauth/test/scenario/CreateRegistrationScenario.java
powerauth-load-tests/src/test/java/com/wultra/security/powerauth/test/scenario/ListOperationHistoryScenario.java
powerauth-load-tests/src/test/java/com/wultra/security/powerauth/test/shared/SessionDataUtils.java
powerauth-load-tests/src/test/java/com/wultra/security/powerauth/test/simulation/PerformanceTestSimulation.java
powerauth-load-tests/src/test/resources/.perf_test_config
powerauth-load-tests/src/test/resources/run_data_prepare.sh
powerauth-load-tests/src/test/resources/run_perf_tests.sh

- move token creation to prep phase
- comment out wiremock stop
- save token id and secret to shared json "cache"

Fix #448: Update Perf Test scenarios

---

powerauth-fido2-tests/src/main/java/com/wultra/security/powerauth/fido2/configuration/PowerAuthWebServiceConfiguration.java

Fix #463: Invalid configuration class PowerAuthWebServiceConfiguration

---

powerauth-fido2-tests/README.md
powerauth-fido2-tests/src/main/java/com/wultra/security/powerauth/fido2/configuration/PowerAuthConfigProperties.java
powerauth-fido2-tests/src/main/java/com/wultra/security/powerauth/fido2/configuration/PowerAuthFido2TestsConfigProperties.java
powerauth-fido2-tests/src/main/java/com/wultra/security/powerauth/fido2/controller/HomeController.java
powerauth-fido2-tests/src/main/resources/application.properties
powerauth-fido2-tests/src/main/resources/templates/login.html
powerauth-fido2-tests/src/main/resources/templates/payment.html
powerauth-fido2-tests/src/main/webapp/resources/js/login.js

Added configuration property to be able to hide advanced settings on property configuration level.

Fix #499: FIDO2 Test application: Property to Hide Advanced Option

---

powerauth-fido2-tests/src/main/resources/templates/login.html
powerauth-fido2-tests/src/main/resources/templates/payment.html
powerauth-fido2-tests/src/main/webapp/resources/css/wultra-login.css

Changing texts as requested by marketing departement.

Fix #513: FIDO2 Test application: Edit texts

---

powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v3x/PowerAuthApplicationConfigurationTest.java

Fix #493: Add test for OIDC configuration endpoint

---

powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v32/PowerAuthOidcActivationTest.java

Fix #506: Add test for OIDC PKCE

---

powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v3x/PowerAuthApplicationConfigurationTest.java

Fix configuration of PowerAuthApplicationConfigurationTest

---

powerauth-test-server/Dockerfile

Fix tomcat hash in Dockerfile

---

powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v3x/PowerAuthApplicationConfigurationTest.java

Configure Base URI string for encryption tests

---

.github/workflows/build-powerauth-fido2-tests-docker-image.yml

(cherry picked from commit f4a58ed86152001448227fb38188cbcbad714a7c)

Enhance Docker pipeline: add inputs for registry push and environment selection
